title: Laboratoire SINERGIES
description: Expertise multidisciplinaire en santé et recherche clinique.
url: "https://servopuma.github.io"
baseurl: "/sinergies"
lang: fr
timezone: Europe/Paris

markdown: kramdown
permalink: pretty

collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projets/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: projects
    values:
      layout: project

exclude:
  - .bundle
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
  - outputs
  - scripts
  - tools
  - vendor
